/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Supermercado;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class jifListadoNombre extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaporNombreView
     */
    private DefaultTableModel modelo = new DefaultTableModel();
    public jifListadoNombre() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlIngrese = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jlTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlTitulo.setText("Listado por Nombre");

        jlIngrese.setText("Ingrese Descripcion:");

        jtfDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jtfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDescripcionKeyReleased(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIngrese)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlIngrese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescripcionKeyReleased
        //KeyReleased lo es un evento que se activa cuando el usuario deja de
        //presionar la tecla
        borrarFilas();
        //Si empieza con lo que ponemos en descripcion entonces lo agrega a la tabla
        for (Producto aux : Menu.listaProductos) {
            if (aux.getDescripcion().toLowerCase().startsWith(jtfDescripcion.getText().toLowerCase())) {
                modelo.addRow(new Object[]{
                    aux.getCodigo(),
                    aux.getDescripcion(),
                    aux.getPrecio(),
                    aux.getStock(),
                    aux.getRubro()});
            }
        }
    }//GEN-LAST:event_jtfDescripcionKeyReleased

    private void armarCabecera(){
        modelo.addColumn("codigo");
        modelo.addColumn("descripcion");
        modelo.addColumn("precio");
        modelo.addColumn("stock");
        modelo.addColumn("rubro");
        jTable.setModel(modelo);
    }
    
    private void borrarFilas() {
        //Obtiene la cantidad de valores que coinciden
        int f = jTable.getRowCount() - 1;
        //Conforme avanza va removiendo de la tabla de 1 en 1
        for (; f >= 0; f--) {
            modelo.removeRow(f);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlIngrese;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtfDescripcion;
    // End of variables declaration//GEN-END:variables
}
